=== krakan/cvinit/json/cvschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "CV",
  "description": "A CV for an Init consultant",
  "type": "object",
  "properties": {
    "firstname": {
      "description": "Consultant first name",
      "type": "string"
    },
    "lastname": {
      "description": "Consultant last name",
      "type": "string"
    },
    "image": {
      "description": "Portrait photo file name",
      "type": "string"
    },
    "caption": {
      "description": "Portrait photo caption",
      "type": "string"
    },
    "summary": {
      "description": "CV summary",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "presentation": {
      "description": "Consultant presentation",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "examples": {
      "description": "A few examples of roles, skills and assignments",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "header": {
            "type": "string"
          },
          "descriptions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "assignments": {
      "description": "List of assignments",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customer": {
            "type": "string"
          },
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            }
          }
        }
      }
    },
    "teaching": {
      "description": "List of teaching assignments",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "customer": {
            "type": "string"
          },
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          },
          "title": {
            "type": "string"
          },
          "description": {
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "type": "string"
                },
                {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              ]
            }
          }
        }
      }
    },
    "skills": {
      "description": "List of aquired skills",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "header": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "education": {
      "description": "Courses and exams",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "header": {
            "type": "string"
          },
          "descriptions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "employment": {
      "description": "Previous and current employments",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "role": {
            "type": "string"
          },
          "employer": {
            "type": "string"
          },
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== krakan/cvinit/json/jonas.json
{
  "firstname": "Jonas J",
  "lastname": "Linde",
  "image": "jonas_linde.jpg",
  "caption": "Civilingenjörsexamen i teknisk fysik och beräkningsteknik vid Uppsala Universitet 1992.",
  "summary": [
    "Mycket erfaren systemadministratör och utvecklare med gedigen kunskap om systemadministration och systemutveckling i Unixmiljö med Perl, C, Java och relationsdatabaser.",
    "Jonas har arbetat med de flesta aspekter av systemadministration i Unix- och Linuxmiljö."
  ],
  "presentation": [
    "Jonas är lösningsorienterad, analytisk och klarsynt. Han slår ofta huvudet på spiken. Han är prestigelös men har samtidigt höga kvalitetskrav. Som arbetskamrat är han hjälpsam och humoristisk.",
    "Fritiden ägnar Jonas åt på tok för lite friluftsliv."
  ],
  "examples": [
    {
      "header": "Uppdrag",
      "descriptions": [
        "Verktygsutveckling i Unixmiljöer",
        "Systemadministration i Linux och Unix",
        "Förbättring av system för Continuous Integration",
        "Byggnet, Utveckling av releasehanteringssystem"
      ]
    },
    {
      "header": "Roller",
      "descriptions": [
        "Systemadministratör i Unix och Linux",
        "Systemutvecklare i Unix och Linux",
        "Teamledare med fokus på DevOps",
        "Lärare och mentor"
      ]
    },
    {
      "header": "Kunskaper",
      "descriptions": [
        "Unix, Solaris, Linux, Irix",
        "Oracle, MySQL och PostgreSQL",
        "Java, C++, C, Perl",
        "Git, Chef, Cfengine, WMvare"
      ]
    }
  ],

  "assignments": [
    {
      "customer": "Klarna",
      "from": "okt 2014",
      "to": "dec 2015",
      "title": "Förbättring av konfigurationshantering",
      "description": [
        "Kunden använder Chef för att hantera konfigurationen av olika servrar. Chef ingår i ett större system av verktyg som Jenkins, Jira, Git, Vagrant, och Docker som tillsammans används för kontinuerlig integration och leverans av samtliga delsystem som kunden använder i sina test- och produktionsmiljöer. Med domänkunskap om integrationen mellan utveckling och drift har Jonas bidragit till att säkerställa en stabil konfigurationshantering och ständigt fungerande integration."
      ]
    },
    {
      "customer": "Rikspolisstyrelsen",
      "from": "okt",
      "to": "nov 2014",
      "title": "Konstruktion av säkerhetsprofiler",
      "description": [
        "Polisen deltar i ett internationellt samarbete för att tillgängliggöra biometriska data på passens RFID-chip till deltagande polismyndigheter. För att skydda systemet mot intrång används AppArmor. Jonas har analyserat de olika komponenternas användning och därefter med hjälp av de verktyg som AppArmor tillhandahåller skapat täckande säkerhetsprofiler för dem samt sett till att dessa installeras och konfigureras på rätt sätt med hjälp av en anpassad variant av konfigurations- och provisioneringsverktyget CFE."
      ]
    },
    {
      "customer": "Skatteverket",
      "from": "2014",
      "title": "Förvaltning av provisioneringsverktyg",
      "description": [
        "Skatteverket använder CFE för att hantera installation av programpaket på sina servrar samt i viss utsträckning för konfigurationshantering. Verktyget har fortlöpande anpassats till förändrade behov. Som en del av förvaltningen av Skatteverkets generella unixtillägg (SGUT) har Jonas med hjälp ingående kännedom om CFE särskilt bidragit med förbättring av CFE både när det gäller verktyget som sådant och när det gäller Skatteverkets användnings av det.  "
      ]
    },
    {
      "customer": "Arbetsförmedlingen",
      "from": "2011",
      "title": "Integration",
      "description": [
        "Projektet AIS-F Modernisering syftar till att ersätta den gamla stordatormiljön (BS2000) med en modernare. Detta görs för att säkerställa förvaltning och vidareutveckling på en modern standardiserad plattform vilket medför enklare kompetensförsörjning.",
        "Några delmål var:",
        [
          "att migrera databasen från SESAM till Oracle",
          "att införa ny arkitektur med Solaris och JBoss",
          "att konvertera applikationerna från Cobol till Java",
          "att hantera konfiguration med hjälp av Puppet"
        ],
        "Jonas bidrog med systemkunskap, analysförmåga och verktygsutveckling till att effektivt lösa de utmaningar som projektet medförde."
      ]
    },
    {
      "customer": "Rikspolisstyrelsen",
      "from": "2011",
      "title": "Teknikspecialist",
      "description": [
        "Polisen har en utvecklings- och driftplattform kallad Limbo baserad på Linux, MySQL och JBoss. Många servrar är virtualiserade med VMware och man använder CFEngine för konfigurationshantering. Jonas bidrog med kunskap om dessa tekniker i systemgruppens dagliga arbete."
      ]
    },
    {
      "customer": "Skatteverket",
      "from": "2009",
      "to": "2010",
      "title": "Migrering av skattedatabasen",
      "description": [
        "Skatteverket har i samarbete med HP genomfört en migrering av Sveriges skattedatabas från Unisys till HP-UX. För att underlätta för den del av personalen som jobbar med systemet skapades ett hybridsystem där de metoder och arbetssätt som tidigare använts till stor del bevarades fast miljön bytts ut mot en Unixmiljö. Jonas har ansvarat för administration av Unixmiljön samt utveckling av verktyg i huvudsakligen Perl och Shellscript."
      ]
    },
    {
      "customer": "Skatteverket",
      "from": "2007",
      "to": "2009",
      "title": "Miljöstöd",
      "description": [
        "Skatteverkets miljöer för utveckling och underhåll av applikationer är helt avskiljd från motsvarande driftsmiljöer både avseende hårdvara och personal. Den personal som ansvarar för administrationen av test- och utvecklingsmiljöer jobbar inom uppdraget Miljöstöd. Jonas har där dels arbetat med administration och underhåll samt bistått med expertkunskaper inom bl.a. Perl och CFE."
      ]
    },
    {
      "customer": "Tele2",
      "from": "2006",
      "to": "2007",
      "title": "Administration och driftsupport av internettjänster",
      "description": [
        "I takt med att kundhanteringssystemet för Tele2:s internettjänster vuxit har behovet av support gentemot de nationella bolagen runt om i Europa ökat. Eftersom systemet utvecklas kontinuerligt krävs ständigt nya infallsvinklar för att klara av systerbolagens förväntningar. Samtidigt har komplexiteten på det interna systemet ökat med tjänster som LDAP, ssh, Kerberos, DNS, access listor för åtkomst och administration av den växande serverparken. Jonas har arbetat som systemadministratör med ansvar för ett flertal av systemets komponenter.",
        "Källkoden hanterades i subversion och Jonas hade rollen som teknisk CM."
      ]
    },
    {
      "customer": "Tele2",
      "from": "2003",
      "to": "2006",
      "title": "Utveckling och drift av inloggningsplattform",
      "description": [
        "Utveckling och drift av inloggningsplattformen för Tele2s internettjänster - t ex ADSL, GPRS och UMTS - på Solaris. Plattformen är byggd på ett egenutvecklat applikationsramverk som använts för ett antal större och mindre samverkande system. Mycket av arbetet har gått ut på vidareutveckling av själva ramverket som är skrivet i C. Även inloggningsdelen av systemet har genomgått en utveckling i takt med ökande krav och förväntningar på plattformen. Denna del är konstruerad kring en egenutvecklad radiusserver. Jonas har jobbat huvudsakligen som utvecklare men även med administration av driftmiljön.",
        "Källkoden hanterades i subversion och Jonas hade rollen som teknisk CM."
      ]
    },
    {
      "customer": "Regeringskansliet",
      "from": "dec 2002",
      "to": "feb 2003",
      "title": "Konfigurationshantering",
      "description": [
        "Införande av automatiserad konfigurationshantering med hjälp av cfengine och Inits CFE-ramverk."
      ]
    },
    {
      "customer": "Boxer",
      "from": "2002",
      "title": "Systemadministration",
      "description": [
        "Teknisk hjälp i samband med flytt av Solarisservrar till ny serverhall och översyn av systemet för automatisk start av tjänster."
      ]
    },
    {
      "customer": "Sveriges Television",
      "from": "maj 2002",
      "title": "Felsökning av DNS",
      "description": [
        "Felsökning och åtgärdande av akuta fel i DNS."
      ]
    },
    {
      "customer": "Byggnet",
      "from": "maj",
      "to": "sep 2002",
      "title": "Utveckling stödfunktioner för webbprojekt",
      "description": [
        "Framtagning av releasehanteringssystem. Implementering av upload-funktioner för webbapplikation. Miljö: CVS, Linux, Oracle, Perl, Apache."
      ]
    },
    {
      "customer": "OKQ8",
      "from": "okt 2001",
      "title": "Systemutveckling i Oraclemiljö",
      "description": [
        "Implementering av nya funktioner i en mängd olika system med hjälp av Oracle, Perl, Java, Solaris"
      ]
    },
    {
      "customer": "Spacecoin",
      "from": "jan",
      "to": "okt 2001",
      "title": "Systemadministration och utveckling",
      "description": [
        "Spacecoin har utvecklat en betalningstjänst för digitala varor på Internet. Jonas har arbetat som projektledare med design och konstruktion av tjänstens faktureringssystem. Dessutom har han satt upp driftmiljön vilket bland annat innefattat installation av hårdvara, operativsystem och databaser samt design och installation av övervaknings- och backupsystem allt på Solaris."
      ]
    },
    {
      "customer": "Yesbox",
      "from": "2000",
      "title": "Utveckling av webbaserat mailsystem",
      "description": [
        "Init har utvecklat ett nytt webbaserat mail- och bonus-system åt Yesbox AB.",
        "Jonas har arbetat med design och implementering av olika delsystem i projektet som helt är utvecklat på J2EE-platformen. Förutom serverbaserad Java används tekniker som HTML, Javascript, sendmail/procmail. Som databas används Oracle 8i på Solaris."
